### ISSUE TITLE
Remove space below breadcrumb

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#469]
We lose a lot of space because of:

```css
.ecl-page-header-harmonised__breadcrumb {
    margin-bottom: 2rem;
}
```
Is there an easy way to remove this margin bottom for the breadcrumb on all pages?
